const portfolio = {
  profile: {
    name: "顾涔潇",
    role: "室内 / 空间设计师",
    city: "江苏",
    tagline: "专注住宅空间的设计、呈现与落地",
    summary:
      "我把空间方案、视觉表达和落地沟通放在同一条线上，重点解决客户最关心的三个问题：好不好看、能不能落地、值不值得做。",
  },
  strengths: ["住宅空间", "空间呈现", "方案深化", "软装搭配", "施工配合"],
  stats: [
    { value: "住宅", label: "主要方向" },
    { value: "案例", label: "精选展示" },
    { value: "落地", label: "核心能力" },
  ],
  services: [
    {
      title: "空间方案",
      desc: "从需求整理、动线梳理到平面优化，输出可执行的空间规划。",
    },
    {
      title: "效果呈现",
      desc: "用效果图和视觉草图把方案说清楚，减少沟通偏差。",
    },
    {
      title: "软装建议",
      desc: "围绕材质、色彩和家具搭配，统一空间气质和使用体验。",
    },
    {
      title: "落地配合",
      desc: "在施工阶段持续跟进，让方案尽量靠近最终效果。",
    },
  ],
  process: [
    { step: "01", title: "了解需求", desc: "确认风格偏好、预算、工期和使用场景。" },
    { step: "02", title: "整理方案", desc: "输出平面逻辑、空间关系和关键节点。" },
    { step: "03", title: "视觉确认", desc: "用效果图和材料方向把方案沟通清楚。" },
    { step: "04", title: "推进落地", desc: "配合现场执行，处理修改和细节收口。" },
  ],
  contact: {
    wechat: "cenxiao_Keith",
    phone: "",
    email: "",
  },
  cases: [
    {
      id: "jinding-01",
      title: "上海金顶公寓",
      type: "中古风",
      area: "147㎡",
      stage: "实景 + 效果图",
      coverImage: "/assets/midcentury/case-01-sm.jpg",
      videoFile: "/assets/midcentury/jinding-mini.mp4",
      videoTitle: "上海金顶公寓视频",
      videoNote: "直接在当前案例页内播放，不需要再跳出去。",
      summary: "围绕中古气质做空间节奏控制，把居住感、收纳感和材质温度放进同一套语言里。",
      challenge: "客户希望空间有中古氛围，但不能显得陈旧，也不能把视觉做得太满。",
      move: "用更克制的家具尺度、偏暖的材质组合和更稳的光线层次来控制气质。",
      result: "空间有了明确的风格辨识度，同时保留了日常居住的舒适度和耐看性。",
      toneClass: "tone-sage",
      coverTitle: "上海金顶公寓",
      coverSubtitle: "中古氛围与居住感平衡",
      gallery: [
        { label: "图01", note: "主视角", src: "/assets/midcentury/case-01-sm.jpg" },
        { label: "图02", note: "空间视角", src: "/assets/midcentury/case-02-sm.jpg" },
        { label: "图03", note: "空间视角", src: "/assets/midcentury/case-03-sm.jpg" },
        { label: "图04", note: "空间视角", src: "/assets/midcentury/case-04-sm.jpg" },
        { label: "图05", note: "空间视角", src: "/assets/midcentury/case-05-sm.jpg" },
        { label: "图06", note: "空间视角", src: "/assets/midcentury/case-06-sm.jpg" },
        { label: "图07", note: "空间视角", src: "/assets/midcentury/case-07-sm.jpg" },
        { label: "图08", note: "空间视角", src: "/assets/midcentury/case-08-sm.jpg" },
        { label: "图09", note: "细节", src: "/assets/midcentury/case-09-sm.jpg" },
      ],
    },
    {
      id: "butterfly-01",
      title: "江苏南通蝶湖一号",
      type: "现代风",
      area: "150㎡",
      stage: "实景 + 效果图",
      coverImage: "/assets/modern/case-01-sm.jpg",
      videoFile: "/assets/modern/butterfly-mini.mp4",
      videoTitle: "江苏南通蝶湖一号视频",
      videoNote: "直接在当前案例页内播放，不需要再跳出去。",
      summary: "用更清晰的现代语言处理大户型空间，把效率、秩序和居住氛围统一起来。",
      challenge: "项目面积不小，但客户不希望空间显空，也不希望风格过于用力。",
      move: "通过连续的体块关系、统一的色彩节奏和更清爽的动线组织，减弱空间碎感。",
      result: "整体更简洁、明亮，也更适合长期居住和后续软装延展。",
      toneClass: "tone-terracotta",
      coverTitle: "江苏南通蝶湖一号",
      coverSubtitle: "现代空间与功能秩序",
      gallery: [
        { label: "图01", note: "主视角", src: "/assets/modern/case-01-sm.jpg" },
        { label: "图02", note: "空间视角", src: "/assets/modern/case-02-sm.jpg" },
        { label: "图03", note: "空间视角", src: "/assets/modern/case-03-sm.jpg" },
        { label: "图04", note: "空间视角", src: "/assets/modern/case-04-sm.jpg" },
        { label: "图05", note: "空间视角", src: "/assets/modern/case-05-sm.jpg" },
        { label: "图06", note: "空间视角", src: "/assets/modern/case-06-sm.jpg" },
        { label: "图07", note: "空间视角", src: "/assets/modern/case-07-sm.jpg" },
        { label: "图08", note: "空间视角", src: "/assets/modern/case-08-sm.jpg" },
        { label: "图09", note: "细节", src: "/assets/modern/case-09-sm.jpg" },
      ],
    },
  ],
  videos: [
    {
      title: "现代风视频",
      file: "/assets/modern/butterfly-mini.mp4",
      note: "可作为项目动线或空间漫游展示。",
      coverImage: "/assets/modern/case-01-sm.jpg",
    },
    {
      title: "中古风视频",
      file: "/assets/midcentury/jinding-mini.mp4",
      note: "可作为氛围展示或客户沟通素材。",
      coverImage: "/assets/midcentury/case-01-sm.jpg",
    },
  ],
  kujialeLinks: [
    {
      title: "效果图",
      url: "https://vr.justeasy.cn/view/0917m849945b1v14-1750917714.html",
      note: "点击可打开预览，也可复制链接发给客户。",
    },
  ],
};

module.exports = portfolio;
